services:
  - type: web
    name: pdf-chatbot-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        scope: run
        value: ${SUPABASE_URL}
      - key: SUPABASE_KEY
        scope: run
        value: ${SUPABASE_KEY}
      - key: GROQ_API_KEY
        scope: run
        value: ${GROQ_API_KEY}